version: "3.8"
services:
    mariadb:
        build: ./requirements/mariadb
    nginx:
        build: ./requirements/nginx
    wordpress:
        build: ./requirements/wordpress
networks:
    default:
        external: false
        name: my-network
