version: "3.8"
services:
    mariadb:
        container_name: mariadb
        image: mariadb:gartaud
        build: ./requirements/mariadb
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
        volumes:
            - mariadb-vol:/var/lib/mysql
        networks:
            - default
    nginx:
        container_name: nginx
        image: nginx:gartaud
        build: ./requirements/nginx
        restart: unless-stopped
        ports:
            - "443:443"
        extra_hosts:
            - "gartaud.42.fr:127.0.0.1"
        volumes:
            - wordpress-vol:/var/www/html
        networks:
            - default
    wordpress:
        container_name: wordpress
        image: wordpress:gartaud
        build: ./requirements/wordpress
        restart: unless-stopped
        ports:
            - "9000:9000"
        environment:
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - WP_ADMIN_USER=${WP_ADMIN_USER}
            - WP_ADMIN_PWD=${WP_ADMIN_PWD}
            - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
        networks:
            - default
        depends_on:
            - mariadb
        volumes:
            - wordpress-vol:/var/www/html
networks:
    default:
        external: false
        name: my-network
volumes:
    mariadb-vol:
        driver: local
        driver_opts:
            type: none
            device: /home/gartaud/data/mariadb
            o: bind
    wordpress-vol:
        driver: local
        driver_opts:
            type: none
            device: /home/gartaud/data/wordpress
            o: bind