version: "3.8"
services:
    mariadb:
        build: ./requirements/mariadb
        restart: always
    nginx:
        build: ./requirements/nginx
        restart: always
        ports:
            - "443:443"
        extra_hosts:
            - "gartaud.42.fr:127.0.0.1"
    wordpress:
        build: ./requirements/wordpress
        restart: always
networks:
    default:
        external: false
        name: my-network
